name: Build and deploy site

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - "readingList.csv"
    - "generator.go"

concurrency:
  group: build-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1

      - name: Run generator
        run: go run github.com/codemicro/readingList generateSite

  deploy:
    needs: deploy
    runs-on: ubuntu-latest
    steps:  
      - name: Generate deploy artefact
        run: zip -r ../site.zip *
        working-directory: .site
        
      - name: Publish site
        run: "curl -Lf -X POST -u palmatum-service:${{ secrets.ACCESS_TOKEN }} -F siteName=readingList -F archive=@site.zip https://pages.tdpain.net/-/upload"