name: Build and deploy site

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - "readingList.csv"
    - "cli/generator.go"

concurrency:
  group: build-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1

      - name: Run generator
        run: go run github.com/codemicro/readingList/cli generateSite

      - name: Upload arfefact
        uses: actions/upload-artifact@v3
        with:
          name: built-site
          path: .site
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/download-artifact@v3
        with:
          name: built-site
          path: site

      - name: Generate deploy bundle
        run: zip -r ../deploy-bundle.zip *
        working-directory: site
        
      - name: Publish site
        run: "curl -Lf -X POST -u palmatum-service:${{ secrets.ACCESS_TOKEN }} -F siteName=readingList -F archive=@deploy-bundle.zip https://pages.tdpain.net/-/upload"