name: Build site

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - "readingList.csv"
    - "generator.go"

concurrency: # Prevent two instances of this running at once
  group: deploy-to-ghpages
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1

      - name: Run generator
        run: go run github.com/codemicro/readingList generateSite

      - name: Generate deploy artefact
        run: zip -r ../site.zip *
        
      - name: Publish site
        run: "curl -X POST -u palmatum-service:${{ secrets.ACCESS_TOKEN }} -F siteName=readingList -F archive=@site.zip https://pages.tdpain.net/-/upload
"
